### ISSUE TITLE
khz to mhz conversion is incorrect

### ISSUE THREAD

**Issue by ordago** [GeniusGeeek/PU-converter#2]
https://github.com/GeniusGeeek/pu-converter/blob/accbc2f296cf80caec12fe723bb5b98c3b96c243/puconverter.php#L1438-L1444

frequency_converter(1000, 'khz', 'mhz');

expected: 1

actual: 1000000 

Edit: some other conversions are also wrong

**Comment by GeniusGeeek** [comment]
Okay thanks for feedback, working on it ASAP.

**Comment by GeniusGeeek** [comment]
Please indicate wrong conversions, so it can immediately corrected

**Comment by ordago** [comment]
These are the ones I found to be wrong

ghz => mhz
khz => hz
khz => mhz
khz => ghz

I've only checked frequency and angles.

**Comment by GeniusGeeek** [comment]
Alright fixing them

**Comment by GeniusGeeek** [comment]
Thanks, the error in conversion has been fixed. I will like you to continue on the OOP, as I am yet to transit to OOP, though I will see if I can use your given template to proceed with it.

**Comment by ordago** [comment]
Hi @GeniusGeeek. I had not planned to continue developing on this repo. I'm working now on a personal project. 

Good luck! 👍

**Comment by GeniusGeeek** [comment]
Thanks for your contributions anyways, I can work from there :)
